
message:
    text: Mensaje sin Profile Activo
    to: jpacheco@autentia.com
    replyTo: someone@localhost
    from: jpacheco12@gmail.com
    subject: Mail Default
---
spring:
    profiles: development
message:
    text: Mensaje desde el perfil development
    to: jpacheco@autentia.com
    replyTo: someone@localhost
    from: jpacheco12@gmail.com
    subject: Mail development
---
spring:
    profiles: production
message:
    text: Mensaje desde el perfil produccion
    to: jpacheco@autentia.com
    replyTo: someone@localhost
    from: jpacheco12@gmail.com
    subject: Mail production